version: "3.8"

services:
  frontend:
    depends_on:
      shop:
        condition: service_healthy
    build: ./frontend/
    restart: unless-stopped
    ports:
      - 8081:80
    pids_limit: 64
    mem_limit: 400m
    cpus: 1
  shop:
    build: ./shop/
    restart: unless-stopped
    environment:
      - CACHEADDR=TODO
      - QUEUEADDR=TODO
      - DBADDR=postgres://admin:admin@postgresql:5432/template
      - BINDADDR=0.0.0.0:8000
      - LOGLEVEL=debug
    pids_limit: 64
    mem_limit: 800m
    cpus: 2
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:8000/api/v1/health"]
      interval: 10s
      timeout: 5s
      start_period: 5s
      retries: 5
    depends_on:
      postgresql:
        condition: service_healthy
    # ports:
    #   - 8000:8000
  postgresql:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=template
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    pids_limit: 64
    mem_limit: 800m
    cpus: 2
  # pgadmin:
  #   image: dpage/pgadmin4:7
  #   restart: unless-stopped
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=root
  #   ports:
  #     - 8181:80
