version: '3.8'

services:
  flask_app:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app_network
  
  grpc_server:
    build: 
      context: ./clone_database
      dockerfile: Dockerfile
    networks:
      - app_network

networks:
  app_network: